#' Convert a character object to a format compatible with SQL SELECT
#' 
#' @param in_chr a character vector
#' @return a character vector consisting of a single string with each object separated by 
#' escaped quotes, bracketted by parens.
#' 
#' @examples
#' test <- c("Hspa8","Cux2","Snap25","Rspo2")
#' chr_to_sql(test)
#' 
#' sql_query <- paste0("SELECT * FROM my_table WHERE gene IN ",chr_to_sql(test))
#' print(sql_query)
chr_to_sql <- function(in_chr) {
  result <- paste0("(",paste0("\"",in_chr,"\"",collapse=","),")")
  return(result)
}


#' Evaluate a character string to a numeric vector
chr_to_num <- function(in_chr) {
  result <- eval(parse(text=paste0("round(c(",in_chr,"),0)")))
  return(result)
}


#' Mix two colors additively
#' 
#' @param col1 A hex or R color
#' @param col2 Another hex or R color
#' @return The sum of col1 and col2 as a character hex color (e.g. "#FFFFFF")
#' 
#' @examples
#' color_sum("red","green")
#' 
#' color_sum("#EC008C","#FBB040")
color_sum <- function(col1,col2) {
  
  rgbmat1 <- col2rgb(col1)/255
  rgbmat2 <- col2rgb(col2)/255
  
  mix <- rgbmat1 + rgbmat2
  
  rgb(mix[1],mix[2],mix[3])
  
}


#' Convert font sizes in pt to mm
#' @param pt A numeric font size in pt.
#' @return A numeric font size in mm.
#' 
#' @examples
#' pt2mm(12)
#' 
#' ggplot(mtcars) +
#'   geom_text(aes(x = mpg, y = wt, label = rownames(mtcars)),
#'             size = pt2mm(7))
pt2mm <- function(pt) {
  mm <- pt / 2.834645669
  return(mm)
}


#' Convert the case of Riken genes no matter input case
#' 
#' @param in_chr a character vector of Riken gene symbols
#' @return a character vector with correck Riken capitalization
#' 
#' @examples
#' test <- c("6330527o06RiK","A930038C07RIK","a330070k13rik")
#' riken_case(test)
riken_case <- function(in_chr) {
  upper <- toupper(in_chr)
  result <- sub("RIK","Rik",upper)
  return(result)
}


#' Split a character string by commas, spaces, and tabs
#' 
#' @param in_string a chr string containing commas, spaces, and/or tabs
#' @return a character vector with each object separated by any combination of commas, spaces, and/or tabs
#' 
#' @examples
#' test <- "Hspa8, Scnn1a,Rbp4    Ptgs2"
#' split_chr(test)
split_cst <- function(in_string) {
  out_chr <- strsplit(in_string,"[, \t]+")[[1]]
  return(out_chr)
}


#' Convert the case of objects in a character vector to Title Case
#' 
#' @param in_chr a character vector
#' @return a character vector with Each Object In Title Case
#' 
#' @examples
#' test <- c("hspa8","scnn1a","fhqwghads")
#' title_case(test)
title_case <- function(in_chr) {
  lower <- tolower(in_chr)
  s <- strsplit(lower, " ")
  result <- paste(toupper(substring(s, 1,1)), substring(s, 2), sep="")
  return(result)
}


#' Convert values to colors along a color ramp
#' 
#' @param x a numeric vector to be converted to colors
#' @param minval a number that's used to set the low end of the color scale (default = 0)
#' @param maxval a number that's used to set the high end of the color scale. If NULL (default), 
#' use the highest value in x
#' @param colorset a set of colors to interpolate between using colorRampPalette 
#' (default = c("darkblue","dodgerblue","gray80","orangered","red"))
#' @return a character vector of hex color values generated by colorRampPalette. Color values will
#' remain in the same order as x.
values_to_colors <- function(x, minval = 0, maxval = NULL, colorset = c("darkblue","dodgerblue","gray80","orangered","red")) {
  
  heat_colors <- colorRampPalette(colorset)(1001)
  
  if(is.null(maxval)) {
    maxval <- max(x)
  }
  
  heat_positions <- unlist(round((x - minval) / (maxval - minval) * 1000 + 1, 0))
  
  colors <- heat_colors[heat_positions]
  
  colors
}
